
security:
  basic:
    enabled: false
  
server:
  port: 8083

eureka: 
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl: 
      defaultZone: http://localhost:8761/eureka/

 
logging:
  level:
    com.netflix: WARN
    com.springframework.weeb: WARN
    com.example: DEBUG